apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "adminer.selectorLabels" . | nindent 4 }}
